when:
  event: [push, pull_request]
  branch:
    include: [main, release/*]
    exclude: [test/1.0.0, test/1.1.*]

steps:
  clone:
    image: woodpeckerci/plugin-git
    settings:
      depth: 50

  run-two:
    image: busybox
    commands:
      - echo "second run"

  run-one:
    image: busybox
    depends_on: [clone, run-two]
    commands:
      - echo "first run"

  run-three:
    image: ubuntu
    depends_on: [clone]
    commands:
      - echo "hi"
