when:
  event: [push, pull_request]
  branch:
    include: [main, release/*]
    exclude: [test/1.0.0, test/1.1.*]

steps:
  run-two:
    image: busybox
    commands:
      - echo "second run"

  run-one:
    image: busybox
    depends_on: [run-two]
    commands:
      - echo "first run"

  run-three:
    image: ubuntu
    commands:
      - echo hi