# Pipeline-level event filter
when:
  event: [push, pull_request]
  branch:
    include: [ main, release/* ]
    exclude: [ test/1.0.0, test/1.1.* ]

steps:
  run-one:
    image: busybox
    depends_on: [first]
    commands:
      - echo "first run"
      
  run-two:
    image: busybox
    depends_on: [first]
    commands:
      - echo "second run"

  run-three:
    image: ubuntu
    commands:
      - echo hi
